apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        resources:
          limits:
            cpu: "0.5"
            memory: "50Mi"
        ports:
          - containerPort: 8081
        env: # https://hub.docker.com/_/mongo-express
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                key: mongo-root-username
                name: mongodb-secret
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
            valueFrom:
              secretKeyRef:
                key: mongo-root-username
                name: mongodb-secret
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
          